apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
spec:
  type: LoadBalancer
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort:  8888
